USE RESERVATION;

CREATE TABLE BOOKING (
    BOOKING_ID INT NOT NULL AUTO_INCREMENT,
    P_ID INT NOT NULL,
    B_ID INT NOT NULL,
    DATE_TIME DATETIME,
    SOURCES VARCHAR(255),
    DESIGNATION VARCHAR(255),
    BOOKED_DATE DATE,
    NUMBER_SEAT INT NOT NULL,
    CONSTRAINT PK_BOOKING PRIMARY KEY (BOOKING_ID),
    FOREIGN KEY (P_ID) REFERENCES PASSANGER(P_ID),
	FOREIGN KEY (B_ID) REFERENCES BUS(B_ID)
);

SELECT *
FROM BUS
WHERE B_ID IN (SELECT B_ID
FROM BOOKING);

SELECT * FROM BOOKING;

DESC BOOKING;

-- ALTER TABLE BOOKING
-- ADD COLUMN NUMBER_SEAT INT NOT NULL;
