USE RESERVATION;
CREATE TABLE BUS(
B_ID INT NOT NULL,
B_NAME VARCHAR(255),
B_TYPE VARCHAR(255),
SEAT_TYPE VARCHAR(255),
SEAT_COUNT INT,
CONSTRAINT PK_BUS PRIMARY KEY (B_ID)
);

SELECT * FROM BUS;

INSERT INTO BUS VALUES(1,"RED_BUS","AC","SLEEPER",25),
(2,"TRAVLES_BUS","NON_AC","SEMI_SLEEPER",40),
(3,"ABHI_BUS","AC","SEATER",35),
(4,"SETC_BUS","WINDOWS","SEMI_SLEEPER",27),
(5,"MY_BUS","AC","SEMI_SLEEPER",32);

-- ALTER TABLE BUS
-- MODIFY COLUMN B_NAME VARCHAR(255) NOT NULL,
-- MODIFY COLUMN B_TYPE VARCHAR(255) NOT NULL,
-- MODIFY COLUMN SEAT_TYPE VARCHAR(50) NOT NULL,
-- MODIFY COLUMN SEAT_COUNT INT NOT NULL;

