USE RESERVATION;

CREATE TABLE PASSANGER(
P_ID INT NOT NULL UNIQUE,
FIRST_NAME VARCHAR(255) NOT NULL,
LAST_NAME VARCHAR(255),
AGE INT NOT NULL,
GENDER VARCHAR(255) NOT NULL,
PHONE_NUMBER VARCHAR(255) NOT NULL UNIQUE,
MAIL_ID VARCHAR(255) NOT NULL UNIQUE,
PASSWORD VARCHAR(255) NOT NULL,
CONSTRAINT PK_PASSANGER PRIMARY KEY (P_ID)
);

 -- ALTER TABLE PASSANGER
 -- MODIFY COLUMN PHONE_NUMBER VARCHAR(255);


SELECT * FROM PASSANGER;

DESC PASSANGER;

 -- ALTER TABLE PASSANGER
 -- ADD COLUMN PASSWORD VARCHAR(255);




